=== SK-CERT/csp/deployment/docker/base-images/misp-image/MISP/app/files/taxonomies/schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Validator for misp-taxonomies",
  "id": "https://www.github.com/MISP/misp-taxonomies/schema.json",
  "defs": {
    "entry": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "numerical_value": {
            "type": "number"
          },
          "expanded": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "colour": {
            "type": "string"
          },
          "value": {
            "type": "string"
          },
          "required": [
            "value"
          ]
        }
      }
    },
    "values": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "entry": {
            "$ref": "#/defs/entry"
          },
          "predicate": {
            "type": "string"
          }
        },
        "required": [
          "predicate"
        ]
      }
    },
    "predicates": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "numerical_value": {
            "type": "number"
          },
          "colour": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "expanded": {
            "type": "string"
          },
          "value": {
            "type": "string"
          },
          "required": [
            "value"
          ]
        }
      }
    }
  },
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "version": {
      "type": "integer"
    },
    "description": {
      "type": "string"
    },
    "expanded": {
      "type": "string"
    },
    "namespace": {
      "type": "string"
    },
    "type": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "enum": [
          "org",
          "user",
          "attribute",
          "event"
        ]
      }
    },
    "refs": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "predicates": {
      "$ref": "#/defs/predicates"
    },
    "values": {
      "$ref": "#/defs/values"
    }
  },
  "required": [
    "namespace",
    "description",
    "version",
    "predicates"
  ]
}

=== SK-CERT/csp/deployment/docker/base-images/misp-image/MISP/app/files/taxonomies/osint/machinetag.json
{
  "predicates": [
    {
      "expanded": "Source Type",
      "value": "source-type"
    },
    {
      "expanded": "Lifetime of the information as Open Source Intelligence",
      "value": "lifetime"
    },
    {
      "expanded": "Certainty of the elements mentioned in this Open Source Intelligence",
      "value": "certainty"
    }
  ],
  "version": 7,
  "description": "Open Source Intelligence - Classification (MISP taxonomies)",
  "namespace": "osint",
  "values": [
    {
      "predicate": "source-type",
      "entry": [
        {
          "value": "blog-post",
          "expanded": "Blog post"
        },
        {
          "value": "microblog-post",
          "expanded": "Microblog post like Twitter"
        },
        {
          "value": "technical-report",
          "expanded": "Technical or analysis report"
        },
        {
          "value": "news-report",
          "expanded": "News report"
        },
        {
          "value": "pastie-website",
          "expanded": "Pastie-like website"
        },
        {
          "value": "electronic-forum",
          "expanded": "Electronic forum"
        },
        {
          "value": "mailing-list",
          "expanded": "Mailing-list"
        },
        {
          "value": "block-or-filter-list",
          "expanded": "Block or Filter List"
        },
        {
          "value": "source-code-repository",
          "expanded": "Source code repository"
        },
        {
          "value": "expansion",
          "expanded": "Expansion"
        },
        {
          "value": "automatic-analysis",
          "expanded": "Automatic analysis including dynamic analysis or sandboxes output"
        },
        {
          "value": "automatic-collection",
          "expanded": "Automatic collection including honeypots, spamtramps or equivalent technologies"
        },
        {
          "value": "manual-analysis",
          "expanded": "Manual analysis or investigation"
        },
        {
          "value": "unknown",
          "expanded": "Unknown"
        },
        {
          "value": "other",
          "expanded": "Other source not specified in this list"
        }
      ]
    },
    {
      "entry": [
        {
          "description": "Information available publicly on long-term",
          "expanded": "Perpetual",
          "value": "perpetual"
        },
        {
          "description": "Information available publicly on short-term",
          "expanded": "Ephemeral",
          "value": "ephemeral"
        }
      ],
      "predicate": "lifetime"
    },
    {
      "entry": [
        {
          "description": "100% Certainty",
          "expanded": "100% Certainty",
          "value": "100",
          "numerical_value": 100
        },
        {
          "description": "93% Almost certain",
          "expanded": "93% Almost certain",
          "value": "93",
          "numerical_value": 93
        },
        {
          "description": "75% Probable",
          "expanded": "75% Probable",
          "value": "75",
          "numerical_value": 75
        },
        {
          "description": "50% Chances about even",
          "expanded": "50% Chances about even",
          "value": "50",
          "numerical_value": 50
        },
        {
          "description": "30% Probably not",
          "expanded": "30% Probably not",
          "value": "30",
          "numerical_value": 30
        },
        {
          "description": "7% Almost certainly not",
          "expanded": "7% Almost certainly not",
          "value": "7",
          "numerical_value": 7
        },
        {
          "description": "0% Impossibility",
          "expanded": "0% Impossibility",
          "value": "0",
          "numerical_value": 0
        }
      ],
      "predicate": "certainty"
    }
  ]
}

=== SK-CERT/csp/deployment/docker/base-images/misp-image/MISP/app/files/taxonomies/ecsirt/machinetag.json
{
  "values": [
    {
      "entry": [
        {
          "expanded": "phishing",
          "value": "phishing"
        }
      ],
      "predicate": "fraud"
    },
    {
      "entry": [
        {
          "expanded": "ddos",
          "value": "ddos"
        }
      ],
      "predicate": "availability"
    },
    {
      "entry": [
        {
          "expanded": "spam",
          "value": "spam"
        }
      ],
      "predicate": "abusive-content"
    },
    {
      "entry": [
        {
          "expanded": "scanner",
          "value": "scanner"
        }
      ],
      "predicate": "information-gathering"
    },
    {
      "entry": [
        {
          "expanded": "dropzone",
          "value": "dropzone"
        }
      ],
      "predicate": "information-content-security"
    },
    {
      "entry": [
        {
          "expanded": "malware",
          "value": "malware"
        },
        {
          "expanded": "botnet drone",
          "value": "botnet-drone"
        },
        {
          "expanded": "ransomware",
          "value": "ransomware"
        },
        {
          "expanded": "malware configuration",
          "value": "malware-configuration"
        },
        {
          "expanded": "c&c",
          "value": "c&c"
        }
      ],
      "predicate": "malicious-code"
    },
    {
      "entry": [
        {
          "expanded": "exploit",
          "value": "exploit"
        },
        {
          "expanded": "brute-force",
          "value": "brute-force"
        },
        {
          "expanded": "ids alerts",
          "value": "ids-alert"
        }
      ],
      "predicate": "intrusion-attempts"
    },
    {
      "entry": [
        {
          "expanded": "defacement",
          "value": "defacement"
        },
        {
          "expanded": "compromised",
          "value": "compromised"
        },
        {
          "expanded": "backdoor",
          "value": "backdoor"
        }
      ],
      "predicate": "intrusions"
    },
    {
      "entry": [
        {
          "expanded": "Vulnerable service",
          "value": "vulnerable-service"
        }
      ],
      "predicate": "vulnerable"
    },
    {
      "entry": [
        {
          "expanded": "blacklist",
          "value": "blacklist"
        },
        {
          "expanded": "unknown",
          "value": "unknown"
        }
      ],
      "predicate": "other"
    },
    {
      "entry": [
        {
          "expanded": "Test",
          "value": "test"
        }
      ],
      "predicate": "test"
    }
  ],
  "predicates": [
    {
      "expanded": "Fraud",
      "value": "fraud"
    },
    {
      "expanded": "Availability",
      "value": "availability"
    },
    {
      "expanded": "Abusive Content",
      "value": "abusive-content"
    },
    {
      "expanded": "Information Gathering",
      "value": "information-gathering"
    },
    {
      "expanded": "Information Content Security",
      "value": "information-content-security"
    },
    {
      "expanded": "Malicious Code",
      "value": "malicious-code"
    },
    {
      "expanded": "Intrusion Attempts",
      "value": "intrusion-attempts"
    },
    {
      "expanded": "Intrusions",
      "value": "intrusions"
    },
    {
      "expanded": "Information Security",
      "value": "information-security"
    },
    {
      "expanded": "Vulnerable",
      "value": "vulnerable"
    },
    {
      "expanded": "Other",
      "value": "other"
    },
    {
      "expanded": "Test",
      "value": "test"
    }
  ],
  "version": 1,
  "description": "Incident Classification by the ecsirt.net project WP4 clearinghouse policy and updated by IntelMQ.",
  "namespace": "ecsirt"
}

=== SK-CERT/csp/deployment/docker/base-images/misp-image/MISP/app/files/taxonomies/estimative-language/machinetag.json
{
  "namespace": "estimative-language",
  "expanded": "Estimative language ICD 203",
  "description": "Estimative language to describe quality and credibility of underlying sources, data, and methodologies based Intelligence Community Directive 203 (ICD 203)",
  "version": 2,
  "predicates": [
    {
      "value": "likelihood-probability",
      "expanded": "Likelihood or probability",
      "description": "Properly expresses and explains uncertainties associated with major analytic judgments: Analytic products should indicate and explain the basis for the uncertainties associated with major analytic judgments, specifically the likelihood of occurrence of an event or development, and the analyst's confidence in the basis for this judgment. Degrees of likelihood encompass a full spectrum from remote to nearly certain. Analysts' confidence in an assessment or judgment may be based on the logic and evidentiary base that underpin it, including the quantity and quality of source material, and their understanding of the topic. Analytic products should note causes of uncertainty (e.g., type, currency, and amount of information, knowledge gaps, and the nature of the issue) and explain how uncertainties affect analysis (e.g., to what degree and how a judgment depends on assumptions). As appropriate, products should identify indicators that would alter the levels of uncertainty for major analytic judgments. Consistency in the terms used and the supporting information and logic advanced is critical to success in expressing uncertainty, regardless of whether likelihood or confidence expressions are used."
    }
  ],
  "values": [
    {
      "predicate": "likelihood-probability",
      "entry": [
        {
          "value": "almost-no-chance",
          "expanded": "Almost no chance - remote - 01-05%",
          "numerical_value": 0
        },
        {
          "value": "very-unlikely",
          "expanded": "Very unlikely - highly improbable - 05-20%",
          "numerical_value": 5
        },
        {
          "value": "unlikely",
          "expanded": "Unlikely - improbable (improbably) - 20-45%",
          "numerical_value": 20
        },
        {
          "value": "roughly-even-chance",
          "expanded": "Roughly even change - roughly even odds - 45-55%",
          "numerical_value": 45
        },
        {
          "value": "likely",
          "expanded": "Likely - probable (probably) - 55-80%",
          "numerical_value": 55
        },
        {
          "value": "very-likely",
          "expanded": "Very likely - highly probable - 80-95%",
          "numerical_value": 80
        },
        {
          "value": "almost-certain",
          "expanded": "Almost certain(ly) - nearly certain - 95-99%",
          "numerical_value": 95
        }
      ]
    }
  ]
}
