=== SK-CERT/csp/deployment/docker/base-images/misp-image/MISP/app/files/warninglists/schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Validator for misp-warninglists",
  "id": "https://www.github.com/MISP/misp-warninglists/schema.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "description": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "version": {
      "type": "integer"
    },
    "list": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "type": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "matching_attributes": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "list",
    "description",
    "version",
    "name"
  ]
}

=== SK-CERT/csp/deployment/docker/base-images/misp-image/MISP/app/files/warninglists/lists/microsoft-office365/list.json
{
  "list": [
    "-my.sharepoint.com",
    ".Portal.cloudappsecurity.com",
    ".aadrm.com",
    ".acompli.net",
    ".activedirectory.windowsazure.com",
    ".adhybridhealth.azure.com",
    ".api.skype.com",
    ".appex-rf.msn.com",
    ".appex.bing.com",
    ".asm.skype.com",
    ".assets-yammer.com",
    ".azurerms.com",
    ".blob.core.windows.net",
    ".broadcast.skype.com",
    ".cc.skype.com",
    ".cdn.office.net",
    ".cloudapp.net",
    ".cloudfront.net",
    ".config.skype.com",
    ".conv.skype.com",
    ".cqd.lync.com",
    ".dc.trouter.io",
    ".entrust.net",
    ".geotrust.com",
    ".giphy.com",
    ".glbdns.microsoft.com",
    ".hybridconfiguration.azurewebsites.net",
    ".infra.lync.com",
    ".keydelivery.mediaservices.windows.net",
    ".live.com",
    ".lync.com",
    ".mail.protection.outlook.com",
    ".microsoft.com",
    ".microsoftonline-p.com",
    ".microsoftonline-p.net",
    ".microsoftonline.com",
    ".msecnd.net",
    ".msedge.net",
    ".msg.skype.com",
    ".msocdn.com",
    ".office.com",
    ".office.net",
    ".office365.com",
    ".omniroot.com",
    ".onenote.com",
    ".onmicrosoft.com",
    ".outlook.com",
    ".outlook.office.com",
    ".phonefactor.net",
    ".pipe.aria.microsoft.com",
    ".pipe.skype.com",
    ".portal.cloudappsecurity.com",
    ".protection.outlook.com",
    ".public-trust.com",
    ".queue.core.windows.net",
    ".search.msit.us.trafficmanager.net",
    ".search.production.apac.trafficmanager.net",
    ".search.production.emea.trafficmanager.net",
    ".search.production.us.trafficmanager.net",
    ".servicebus.windows.net",
    ".sharepoint.com",
    ".sharepointonline.com",
    ".store.core.windows.net",
    ".streaming.mediaservices.windows.net",
    ".svc.ms",
    ".symcb.com",
    ".symcd.com",
    ".table.core.windows.net",
    ".um.outlook.com",
    ".users.storage.live.com",
    ".verisign.com",
    ".verisign.net",
    ".windows.net",
    ".yammer.com",
    ".yammerusercontent.com",
    "104.146.0.0/19",
    "104.146.128.0/17",
    "104.208.152.137/32",
    "104.208.28.54/32",
    "104.208.31.113/32",
    "104.208.36.70/32",
    "104.209.144.16/29",
    "104.209.179.144/32",
    "104.209.190.8/32",
    "104.209.212.110/32",
    "104.209.35.177/32",
    "104.210.1.218/32",
    "104.210.208.16/29",
    "104.210.212.243/32",
    "104.210.220.25/32",
    "104.210.4.77/32",
    "104.210.40.87/32",
    "104.210.43.160/32",
    "104.210.48.8/29",
    "104.210.83.160/29",
    "104.211.100.160/32",
    "104.211.100.204/32",
    "104.211.102.225/32",
    "104.211.103.207/32",
    "104.211.152.32/27",
    "104.211.16.16/29",
    "104.211.160.244/32",
    "104.211.161.150/32",
    "104.211.161.165/32",
    "104.211.161.185/32",
    "104.211.162.33/32",
    "104.211.163.139/32",
    "104.211.165.35/32",
    "104.211.166.139/32",
    "104.211.216.32/27",
    "104.211.224.118/32",
    "104.211.225.135/32",
    "104.211.227.110/32",
    "104.211.229.230/32",
    "104.211.231.147/32",
    "104.211.231.248/32",
    "104.211.48.16/29",
    "104.211.54.134/32",
    "104.211.54.99/32",
    "104.211.88.16/28",
    "104.211.98.138/32",
    "104.211.98.146/32",
    "104.211.98.246/32",
    "104.211.99.236/32",
    "104.214.144.252/32",
    "104.214.144.62/32",
    "104.214.145.173/32",
    "104.214.146.199/32",
    "104.214.35.244/32",
    "104.214.38.136/32",
    "104.215.144.64/29",
    "104.215.146.200/32",
    "104.215.184.16/29",
    "104.215.194.17/32",
    "104.215.198.144/32",
    "104.215.96.24/29",
    "104.40.178.127/32",
    "104.40.179.160/32",
    "104.40.208.40/32",
    "104.40.214.0/32",
    "104.40.218.31/32",
    "104.40.225.204/32",
    "104.40.234.17/32",
    "104.40.240.48/28",
    "104.40.28.30/32",
    "104.40.75.8/32",
    "104.40.76.196/32",
    "104.40.91.215/32",
    "104.41.13.120/29",
    "104.41.155.129/32",
    "104.41.207.112/32",
    "104.41.207.73/32",
    "104.41.210.140/32",
    "104.41.216.16/28",
    "104.41.35.170/32",
    "104.41.62.54/32",
    "104.42.225.143/32",
    "104.42.229.230/32",
    "104.42.230.91/32",
    "104.42.231.28/32",
    "104.42.72.16/29",
    "104.43.12.164/32",
    "104.43.140.223/32",
    "104.43.208.16/29",
    "104.43.235.252/32",
    "104.43.240.16/29",
    "104.44.195.0/24",
    "104.44.200.0/23",
    "104.44.218.128/25",
    "104.44.254.128/25",
    "104.44.255.0/25",
    "104.45.0.16/28",
    "104.45.11.195/32",
    "104.45.208.104/29",
    "104.45.214.112/32",
    "104.45.225.7/32",
    "104.45.231.95/32",
    "104.46.1.211/32",
    "104.46.101.116/32",
    "104.46.105.95/32",
    "104.46.112.8/29",
    "104.46.224.64/28",
    "104.46.38.64/32",
    "104.46.50.125/32",
    "104.46.96.162/32",
    "104.46.97.194/32",
    "104.47.0.0/17",
    "104.47.156.62/32",
    "111.221.101.75/32",
    "111.221.104.43/32",
    "111.221.111.196/32",
    "111.221.112.0/21",
    "111.221.122.192/26",
    "111.221.76.128/25",
    "111.221.77.0/26",
    "13.106.56.0/25",
    "13.107.12.51/32",
    "13.107.18.10/31",
    "13.107.19.10/31",
    "13.107.3.0/24",
    "13.107.6.150/31",
    "13.107.6.152/31",
    "13.107.6.156/31",
    "13.107.6.158/31",
    "13.107.6.160/32",
    "13.107.6.168/32",
    "13.107.64.0/18",
    "13.107.7.190/31",
    "13.107.8.0/24",
    "13.107.9.150/31",
    "13.107.9.152/31",
    "13.107.9.156/31",
    "13.107.9.158/31",
    "13.107.9.160/32",
    "13.107.9.168/32",
    "13.66.58.59/32",
    "13.67.186.105/32",
    "13.67.209.156/32",
    "13.67.214.76/32",
    "13.67.222.144/32",
    "13.67.234.27/32",
    "13.67.50.224/29",
    "13.67.53.38/32",
    "13.67.56.225/32",
    "13.67.56.73/32",
    "13.67.59.89/32",
    "13.68.218.89/32",
    "13.68.31.102/32",
    "13.69.159.30/32",
    "13.69.187.20/32",
    "13.70.156.147/32",
    "13.70.156.206/32",
    "13.70.159.107/32",
    "13.70.184.242/32",
    "13.70.185.128/32",
    "13.70.189.101/32",
    "13.70.189.149/32",
    "13.70.89.162/32",
    "13.71.145.114/32",
    "13.71.151.88/32",
    "13.71.155.176/32",
    "13.73.106.160/32",
    "13.73.109.13/32",
    "13.73.155.42/32",
    "13.75.125.228/32",
    "13.75.149.223/32",
    "13.75.153.216/32",
    "13.75.154.195/32",
    "13.75.158.234/32",
    "13.75.159.17/32",
    "13.75.159.51/32",
    "13.75.42.168/32",
    "13.75.42.223/32",
    "13.75.47.241/32",
    "13.75.47.33/32",
    "13.75.48.16/29",
    "13.75.80.16/29",
    "13.76.140.48/32",
    "13.76.188.52/32",
    "13.76.189.79/32",
    "13.76.218.117/32",
    "13.76.219.191/32",
    "13.76.219.210/32",
    "13.77.5.70/32",
    "13.77.7.84/32",
    "13.78.112.190/32",
    "13.78.114.39/32",
    "13.78.120.69/32",
    "13.78.120.70/32",
    "13.78.120.99/32",
    "13.78.122.54/32",
    "13.78.58.132/32",
    "13.78.93.8/32",
    "13.78.94.7/32",
    "13.78.95.252/32",
    "13.79.161.29/32",
    "13.82.54.72/32",
    "13.84.216.209/32",
    "13.84.219.100/32",
    "13.84.222.249/32",
    "13.85.84.102/32",
    "13.88.17.54/32",
    "13.88.183.247/32",
    "13.88.241.210/32",
    "13.88.248.161/32",
    "13.88.254.212/32",
    "13.89.44.84/32",
    "13.91.108.91/32",
    "13.91.252.242/32",
    "13.91.40.251/32",
    "13.91.98.185/32",
    "13.92.136.118/32",
    "13.92.181.66/32",
    "13.92.236.241/32",
    "13.92.80.132/32",
    "13.93.164.45/32",
    "13.93.209.18/32",
    "13.93.219.105/32",
    "13.93.226.103/32",
    "13.94.209.165/32",
    "13.94.47.37/32",
    "13.95.233.176/32",
    "13.95.236.192/32",
    "13.95.88.228/32",
    "131.253.120.128/32",
    "131.253.128.0/19",
    "131.253.160.0/20",
    "131.253.33.215/32",
    "132.245.0.0/16",
    "132.245.0.0/24",
    "132.245.1.0/25",
    "132.245.112.0/24",
    "132.245.113.0/25",
    "134.170.0.0/25",
    "134.170.113.192/26",
    "134.170.115.128/25",
    "134.170.132.0/24",
    "134.170.140.0/24",
    "134.170.148.0/22",
    "134.170.170.86/32",
    "134.170.172.128/25",
    "134.170.200.0/21",
    "134.170.208.0/21",
    "134.170.27.86/32",
    "134.170.48.20/32",
    "134.170.48.22/32",
    "134.170.54.0/26",
    "134.170.54.128/25",
    "134.170.65.86/32",
    "134.170.67.0/25",
    "134.170.68.0/23",
    "137.116.132.4/32",
    "137.116.156.3/32",
    "137.116.157.126/32",
    "137.116.159.19/32",
    "137.116.159.228/32",
    "137.116.172.39/32",
    "137.116.248.150/32",
    "137.116.66.126/32",
    "137.116.74.190/32",
    "137.116.77.120/32",
    "137.116.81.187/32",
    "137.117.109.221/32",
    "137.117.17.124/32",
    "137.135.51.71/32",
    "137.135.52.204/32",
    "137.135.65.72/32",
    "138.91.155.70/32",
    "138.91.159.117/32",
    "138.91.160.172/32",
    "138.91.164.243/32",
    "138.91.245.66/32",
    "138.91.61.107/32",
    "157.55.130.0/25",
    "157.55.133.0/25",
    "157.55.139.177/32",
    "157.55.145.0/25",
    "157.55.155.0/25",
    "157.55.177.39/32",
    "157.55.184.223/32",
    "157.55.227.192/26",
    "157.55.234.0/24",
    "157.55.238.0/25",
    "157.55.40.128/25",
    "157.55.45.128/25",
    "157.55.59.128/25",
    "157.55.80.94/32",
    "157.56.106.128/28",
    "157.56.110.0/23",
    "157.56.112.0/24",
    "157.56.151.0/25",
    "157.56.232.0/21",
    "157.56.240.0/20",
    "157.56.53.128/25",
    "157.56.55.0/25",
    "157.56.58.0/25",
    "157.56.96.16/28",
    "157.56.96.224/28",
    "168.61.100.177/32",
    "168.61.146.25/32",
    "168.61.149.17/32",
    "168.61.152.29/32",
    "168.61.155.249/32",
    "168.61.170.80/32",
    "168.61.172.71/32",
    "168.62.104.83/32",
    "168.62.106.224/32",
    "168.62.204.209/32",
    "168.62.29.225/32",
    "168.62.43.8/32",
    "168.63.100.61/32",
    "168.63.138.56/32",
    "168.63.14.15/32",
    "168.63.172.54/32",
    "168.63.18.79/32",
    "168.63.213.238/32",
    "168.63.219.57/32",
    "168.63.234.40/32",
    "168.63.245.120/32",
    "168.63.29.74/32",
    "168.63.92.133/32",
    "191.232.0.0/23",
    "191.232.2.128/25",
    "191.232.96.0/19",
    "191.233.80.151/32",
    "191.233.95.169/32",
    "191.234.128.0/21",
    "191.234.140.0/22",
    "191.234.19.21/32",
